apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: flux-system
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: bharamicrosystems/nginx:v2
        ports:
        - containerPort: 80
        envFrom:
        - secretRef:
            name: db-passwd

