piVersion: v1
kind: Service
metadata:
          name: nginx-service
            namespace: flux-system
            spec:
                      selector:
                                  app: nginx
                                    ports:
                                                - port: 80
                                                        targetPort: 80
                                                          type: LoadBalance
